baseURL = "https://ne555.io/"
languageCode = "en-us"
title = "Nico Einsidler."
theme = "nicoeinsidler"
sectionPagesMenu = "nav"
publishDir = "docs"

[params]
  author = "Nico Einsidler"
  description = "Nico Einsidler's personal homepage."
  custom_css = ["css/style.css"]
